spring:
  application:
    name: backend-core

  management:
    endpoints:
      web:
        exposure:
          include: prometheus

  # Uncomment and configure the following sections as needed:

  # datasource:
  #   url: jdbc:postgresql://127.0.0.1:5432/taskman
  #   username: user
  #   password: 1234
  #   driver-class-name: org.postgresql.Driver

  # jpa:
  #   hibernate:
  #     ddl-auto: create-drop
  #   show-sql: true
  #   properties:
  #     hibernate:
  #       format_sql: true
  #   open-in-view: false

  # flyway:
  #   enabled: true
  #   baseline-on-migrate: true
  #   locations: classpath:db/migration
